# Generated by Django 6.0.1 on 2026-02-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('FILME', 'Filme'), ('SERIE', 'Série'), ('LIVRO', 'Livro'), ('ARTIGO', 'Artigo Acadêmico'), ('MUSICAL', 'Musical / Teatro'), ('PODCAST', 'Podcast')], max_length=20, verbose_name='Tipo de Mídia')),
                ('sinopse', models.TextField(blank=True, null=True, verbose_name='Sinopse / Descrição')),
                ('autor_diretor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Autor ou Diretor')),
                ('ano_lancamento', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Lançamento')),
                ('link_acesso', models.URLField(blank=True, null=True, verbose_name='Link para acessar (Netflix, PDF, YouTube)')),
                ('url_capa', models.URLField(blank=True, null=True, verbose_name='URL da Imagem de Capa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos do Acervo',
                'ordering': ['-criado_em'],
            },
        ),
    ]
