# Generated by Django 6.0.1 on 2026-02-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.CharField(choices=[('FILME', 'Filme'), ('SERIE', 'Série'), ('LIVRO', 'Livro'), ('ARTIGO', 'Artigo Acadêmico'), ('PODCAST', 'Podcast')], max_length=20, verbose_name='Tipo de Mídia'),
        ),
    ]
