# Generated by Django 6.0.1 on 2026-02-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_recurso_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recurso',
        ),
    ]
