# Generated by Django 6.0.1 on 2026-03-25 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_geral', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Nota Geral para a Plataforma')),
                ('nota_usabilidade', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Facilidade de Uso (Usabilidade)')),
                ('nota_acessibilidade', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Acessibilidade e Inclusão')),
                ('nota_design', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Design e Visual')),
                ('probabilidade_recomendar', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Qual a probabilidade de você recomendar o Crivo para um amigo? (0 a 10)')),
                ('feedback_aberto', models.TextField(blank=True, verbose_name='Sugestões, críticas ou elogios (Opcional)')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_plataforma', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação da Plataforma',
                'verbose_name_plural': 'Avaliações da Plataforma',
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_erro', models.URLField(blank=True, max_length=500, verbose_name='Onde o erro aconteceu?')),
                ('descricao', models.TextField(verbose_name='Descrição do Bug')),
                ('print_tela', models.ImageField(blank=True, null=True, upload_to='bugs/', verbose_name='Print da Tela (Opcional)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ANALISE', 'Em Análise'), ('RESOLVIDO', 'Resolvido'), ('DESCARTADO', 'Descartado')], default='PENDENTE', max_length=20)),
                ('data_reporte', models.DateTimeField(auto_now_add=True)),
                ('resolucao', models.TextField(blank=True, verbose_name='Nota de Resolução (Para o Admin anotar o que fez)')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs_reportados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Bug',
                'verbose_name_plural': 'Reportes de Bugs',
                'ordering': ['-data_reporte'],
            },
        ),
    ]
