# Generated by Django 6.0.1 on 2026-03-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topico',
            name='conteudo_original',
            field=models.TextField(blank=True, help_text='Visível apenas para admins', null=True),
        ),
        migrations.AddField(
            model_name='topico',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topico',
            name='editado',
            field=models.BooleanField(default=False),
        ),
    ]
