# Generated by Django 6.0.1 on 2026-03-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topico',
            name='outra_categoria',
            field=models.CharField(blank=True, help_text="Se selecionou 'Outro', especifique aqui.", max_length=100, null=True),
        ),
    ]
