# Generated by Django 6.0.1 on 2026-03-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_topico_conteudo_original_topico_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, verbose_name='Motivo da Rejeição/Ocultação (Admin)'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('OCULTO', 'Ocultado pela Moderação')], default='APROVADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='topico',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, verbose_name='Motivo da Rejeição/Ocultação (Admin)'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('OCULTO', 'Ocultado pela Moderação')], default='APROVADO', max_length=20),
        ),
    ]
