# Generated by Django 6.0.1 on 2026-05-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_resposta_motivo_rejeicao_alter_resposta_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='conteudo_original',
            field=models.TextField(blank=True, help_text='Visível apenas para admins', null=True),
        ),
        migrations.AddField(
            model_name='resposta',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resposta',
            name='editado',
            field=models.BooleanField(default=False),
        ),
    ]
