# Generated by Django 6.0.1 on 2026-03-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_topico_outra_categoria'),
        ('forum', '0003_popular_categorias'),
    ]

    operations = [
    ]
