# Generated by Django 6.0.1 on 2026-03-05 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_merge_20260304_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhas', to='forum.resposta'),
        ),
    ]
