# Generated by Django 6.0.1 on 2026-02-05 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Sobre mim')),
                ('descricao_fisica', models.TextField(blank=True, verbose_name='Descrição Física (Acessibilidade)')),
                ('pais', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('estado', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=50, verbose_name='Gênero')),
                ('genero_outro', models.CharField(blank=True, max_length=50, verbose_name='Gênero (Outro)')),
                ('pronomes', models.CharField(blank=True, max_length=50, verbose_name='Pronomes')),
                ('is_pcd', models.BooleanField(default=False, verbose_name='Sou Pessoa com Deficiência')),
                ('cid', models.CharField(blank=True, max_length=20, null=True, verbose_name='CID (Opcional)')),
                ('is_profissional_saude', models.BooleanField(default=False, verbose_name='Profissional de Saúde')),
                ('profissao', models.CharField(blank=True, max_length=100)),
                ('conselho', models.CharField(blank=True, max_length=50)),
                ('registro_profissional', models.CharField(blank=True, max_length=50, verbose_name='Nº Registro')),
                ('uf_registro', models.CharField(blank=True, max_length=2, verbose_name='UF do Registro')),
                ('exibir_registro', models.BooleanField(default=False, verbose_name='Exibir registro no perfil?')),
                ('is_familiar', models.BooleanField(default=False, verbose_name='Familiar / Cuidador')),
                ('is_educador', models.BooleanField(default=False, verbose_name='Educador / Pesquisador')),
                ('is_estudante', models.BooleanField(default=False, verbose_name='Estudante')),
                ('is_aliado', models.BooleanField(default=False, verbose_name='Aliado / Interessado')),
                ('show_badges', models.BooleanField(default=True, verbose_name='Mostrar Badges')),
                ('show_bio', models.BooleanField(default=True, verbose_name='Mostrar Bio')),
                ('show_descricao_fisica', models.BooleanField(default=True, verbose_name='Mostrar Desc. Física')),
                ('show_localizacao', models.BooleanField(default=True, verbose_name='Mostrar Localização')),
                ('show_idade', models.BooleanField(default=False, verbose_name='Mostrar Faixa Etária')),
                ('show_genero', models.BooleanField(default=True, verbose_name='Mostrar Gênero')),
                ('show_pronomes', models.BooleanField(default=True, verbose_name='Mostrar Pronomes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
