# Generated by Django 6.0.1 on 2026-02-06 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Sobre mim')),
                ('descricao_fisica', models.TextField(blank=True, verbose_name='Descrição Física (Acessibilidade)')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('pais', models.CharField(choices=[('BR', 'Brasil'), ('PT', 'Portugal'), ('US', 'Estados Unidos'), ('OUTRO', 'Outro')], default='BR', max_length=100, verbose_name='País')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('ESTR', 'Estrangeiro/Outro')], max_length=25, verbose_name='Estado/UF')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NB', 'Não-binário'), ('PNA', 'Prefiro não informar'), ('OUTRO', 'Outro (Especificar)')], max_length=20)),
                ('genero_outro', models.CharField(blank=True, max_length=50)),
                ('pronomes', models.CharField(blank=True, choices=[('ELE', 'Ele/Dele'), ('ELA', 'Ela/Dela'), ('ELU', 'Elu/Delu'), ('QUALQUER', 'Qualquer um'), ('PNA', 'Prefiro não informar'), ('OUTRO', 'Outro (Especificar)')], max_length=20)),
                ('pronomes_outro', models.CharField(blank=True, max_length=50)),
                ('tema_prefiro_nao', models.BooleanField(default=False, verbose_name='Prefiro não informar relação com o tema')),
                ('is_pcd', models.BooleanField(default=False, verbose_name='Sou Pessoa com Deficiência')),
                ('cid', models.CharField(blank=True, max_length=50, null=True, verbose_name='CID')),
                ('is_profissional_saude', models.BooleanField(default=False, verbose_name='Profissional de Saúde')),
                ('profissao', models.CharField(blank=True, max_length=100)),
                ('conselho', models.CharField(blank=True, max_length=50)),
                ('registro_profissional', models.CharField(blank=True, max_length=50)),
                ('uf_registro', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('ESTR', 'Estrangeiro/Outro')], max_length=4, verbose_name='UF do Conselho')),
                ('exibir_registro', models.BooleanField(default=False)),
                ('is_aliado', models.BooleanField(default=False, verbose_name='Aliado / Interessado')),
                ('aliado_familiar', models.BooleanField(default=False)),
                ('aliado_educador', models.BooleanField(default=False)),
                ('aliado_estudante', models.BooleanField(default=False)),
                ('aliado_apenas', models.BooleanField(default=False)),
                ('show_bio', models.BooleanField(default=True)),
                ('show_descricao_fisica', models.BooleanField(default=True)),
                ('show_localizacao', models.BooleanField(default=True)),
                ('show_genero', models.BooleanField(default=True)),
                ('show_pronomes', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
