# Generated by Django 6.0.1 on 2026-03-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alto_contraste',
            field=models.BooleanField(default=False, verbose_name='Alto Contraste'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fonte_dislexia',
            field=models.BooleanField(default=False, verbose_name='Fonte para Dislexia'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='modo_escuro',
            field=models.BooleanField(default=False, verbose_name='Modo Escuro'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ocultar_avaliacoes',
            field=models.BooleanField(default=False, verbose_name='Ocultar minhas avaliações do Acervo no perfil público'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receber_notificacoes',
            field=models.BooleanField(default=True, verbose_name='Receber Notificações por E-mail'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reduzir_animacoes',
            field=models.BooleanField(default=False, verbose_name='Reduzir Animações (Motion)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tamanho_fonte',
            field=models.CharField(choices=[('P', 'Pequena'), ('M', 'Média (Padrão)'), ('G', 'Grande')], default='M', max_length=1, verbose_name='Tamanho da Fonte'),
        ),
    ]
