# Generated by Django 6.0.1 on 2026-03-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_alto_contraste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fonte_tdah',
            field=models.BooleanField(default=False, verbose_name='Fonte TDAH (Leitura Dinâmica)'),
        ),
    ]
