# Generated by Django 6.0.1 on 2026-03-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_fonte_tdah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tamanho_fonte',
            field=models.CharField(choices=[('XP', 'Extra Pequena'), ('P', 'Pequena'), ('M', 'Média (Padrão)'), ('G', 'Grande'), ('XG', 'Extra Grande')], default='M', max_length=2, verbose_name='Tamanho da Fonte'),
        ),
    ]
