# Generated by Django 6.0.1 on 2026-03-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_tamanho_fonte'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='motivo_banimento',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Banimento'),
        ),
    ]
