# Generated by Django 6.0.1 on 2026-03-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_motivo_banimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='data_banimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Banimento'),
        ),
    ]
