# Generated by Django 6.0.1 on 2026-03-19 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Recurso')),
                ('tipo', models.CharField(choices=[('IMAGEM', 'Imagem / Infográfico'), ('VIDEO', 'Vídeo (Upload)'), ('AUDIO', 'Áudio / Podcast (Upload)'), ('PDF', 'Documento (PDF)'), ('EMBED', 'Vídeo/Podcast (YouTube/Spotify)'), ('LINK', 'Link Externo (Artigos/Sites)')], default='IMAGEM', max_length=15)),
                ('descricao', models.TextField(verbose_name='Descrição / Legenda')),
                ('arquivo', models.FileField(blank=True, help_text='Faça o upload do arquivo aqui se não for Link ou Embed.', null=True, upload_to='educacao/arquivos/')),
                ('capa', models.ImageField(blank=True, help_text='Capa ilustrativa (ideal para links externos e áudios).', null=True, upload_to='educacao/capas/')),
                ('codigo_incorporacao', models.TextField(blank=True, help_text='Cole aqui o código <iframe...> fornecido pelo YouTube, Spotify, etc.', null=True, verbose_name='Código de Incorporação (Iframe)')),
                ('url_externa', models.URLField(blank=True, help_text="Obrigatório se o tipo for 'Link Externo'.", null=True, verbose_name='Link Externo')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurso Educativo',
                'verbose_name_plural': 'Recursos Educativos',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
