# Generated by Django 6.0.1 on 2026-03-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursoeducativo',
            name='baixar_pdf',
            field=models.BooleanField(default=False, help_text='Marque para o botão fazer o download. Desmarque para o PDF abrir em uma nova aba.', verbose_name='Forçar download do PDF?'),
        ),
        migrations.AlterField(
            model_name='recursoeducativo',
            name='arquivo',
            field=models.FileField(blank=True, help_text='Upload do arquivo (PDF, Vídeo, Áudio ou Imagem).', null=True, upload_to='educacao/arquivos/'),
        ),
        migrations.AlterField(
            model_name='recursoeducativo',
            name='capa',
            field=models.ImageField(blank=True, help_text='Capa ilustrativa (ideal para Links, Áudios ou PDFs).', null=True, upload_to='educacao/capas/'),
        ),
        migrations.AlterField(
            model_name='recursoeducativo',
            name='codigo_incorporacao',
            field=models.TextField(blank=True, help_text='Cole aqui o código <iframe...> fornecido pelo YouTube ou Spotify.', null=True, verbose_name='Código de Incorporação (Iframe)'),
        ),
        migrations.AlterField(
            model_name='recursoeducativo',
            name='url_externa',
            field=models.URLField(blank=True, null=True, verbose_name='Link Externo'),
        ),
    ]
