# Generated by Django 6.0.1 on 2026-03-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0002_recursoeducativo_baixar_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursoeducativo',
            name='arquivo',
            field=models.FileField(blank=True, help_text='Upload do arquivo (PDF, MP3, MP4, JPG, PNG).', null=True, upload_to='educacao/arquivos/'),
        ),
        migrations.AlterField(
            model_name='recursoeducativo',
            name='codigo_incorporacao',
            field=models.TextField(blank=True, help_text="Cole o código '<iframe...>' do YouTube ou Spotify.", null=True, verbose_name='Código de Incorporação (Iframe)'),
        ),
        migrations.AlterField(
            model_name='recursoeducativo',
            name='tipo',
            field=models.CharField(choices=[('IMAGEM', 'Imagem / Infográfico'), ('VIDEO', 'Vídeo (Upload Local)'), ('AUDIO', 'Áudio (Upload Local)'), ('PDF', 'Documento (PDF)'), ('EMBED', 'Vídeo/Podcast (YouTube/Spotify)'), ('LINK', 'Link Externo (Artigos/Sites)')], default='IMAGEM', max_length=15),
        ),
        migrations.AlterField(
            model_name='recursoeducativo',
            name='url_externa',
            field=models.URLField(blank=True, null=True, verbose_name='URL Externa'),
        ),
    ]
