# Generated by Django 6.0.1 on 2026-03-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0003_alter_recursoeducativo_arquivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursoeducativo',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Descreva a imagem/capa para pessoas com deficiência visual (leitores de tela).', max_length=255, null=True, verbose_name='Texto Alternativo da Imagem (Acessibilidade)'),
        ),
        migrations.AlterField(
            model_name='recursoeducativo',
            name='baixar_pdf',
            field=models.BooleanField(default=False, help_text='Marque para o botão fazer o download. Desmarque para abrir em nova aba.', verbose_name='Forçar download do PDF?'),
        ),
    ]
