# Generated by Django 6.0.1 on 2026-04-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0004_recursoeducativo_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursoeducativo',
            name='alt_text',
            field=models.TextField(blank=True, help_text='Descreva a imagem/capa para pessoas com deficiência visual (leitores de tela).', null=True, verbose_name='Texto Alternativo da Imagem (Acessibilidade)'),
        ),
    ]
